-d C:\Users\asus\Desktop\trafiksinyalodev\impl\gwsynthesis\trafiksinyalodev.vg
-p GW1NZ-1-QFN48-6
-pn GW1NZ-LV1QN48C6/I5
-cst C:\Users\asus\Desktop\trafiksinyalodev\src\trafiksinyalodev.cst
-cfg C:\Users\asus\Desktop\trafiksinyalodev\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 10
